atrayi/config/routes.rb
Atrayi::Application.routes.draw do
	resources :users do
		resources :posts
	end

  root :to => 'users#index'

end

atrayi/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
  attr_accessible :title, :description
end

atrayi/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	attr_accessible :name, :email, :roll, :dept, :age, :contact_no
	validates_length_of :name, :minimum=>2
	validates :name, :presence => true
	validates :email, :presence => true, :uniqueness=>true
		
before_create do |user|
	user.name=user.name.capitalize
	#if user.save!	
end
end

atrayi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

atrayi/app/controllers/posts_controller.rb
class PostsController < ApplicationController
def index
 	@user =User.find(params[:user_id])
  	@posts=@user.posts.find(:all)
end

def new
@post=Post.new
end

def create
user=User.find(params[:user_id])
post=user.posts.create(params[:post])
redirect_to user_path(user)
end
def show
@user =User.find(params[:user_id])
@post=@user.posts.find(params[:id])
end

def edit
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
end

def update
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
@post.update_attributes(params[:post])
@post.save!
redirect_to user_post_path(@user)
end

def destroy
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
@post.destroy
redirect_to user_posts_path(@user)
end
end

atrayi/app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
	@users=User.all
end
def show
	@user=User.find(params[:id])
end
def create
	@user=User.create(params[:user])
	if @user.save
		Usermailer.welcome_email(@user).deliver
		#:notice => 'User was successfully created.'
	else
		render :action=>'create'
	end
	redirect_to users_path 
end
def new
	@user=User.new	
end
def destroy
	user=User.find(params[:id])
	user.destroy
	redirect_to users_path
end
def edit
	@user=User.find(params[:id])
end
def update
	user=User.find(params[:id])
	user.update_attributes(params[:user])
	if user.save!
		redirect_to users_path
	else
		render :action=>'edit'
	end
end
end

atrayi/app/helpers/application_helper.rb
module ApplicationHelper
end

atrayi/app/helpers/posts_helper.rb
module PostsHelper
end

atrayi/app/helpers/users_helper.rb
module UsersHelper
end

atrayi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atrayi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

atrayi/app/views/layouts/shared_documents/_footer.html.erb
<p style="font-family:arial;color:red;font-size:15px;">created by:- Atrayi Sinha</p>

atrayi/app/views/layouts/shared_documents/_header.html.erb
<p style="font-family:arial;color:blue;font-size:20px;"><img src="../assets/icon.ico" alt="Icon" width="68" height="68">
Fakebook</p>

atrayi/app/views/posts/edit.html.erb
<html>
<body style="background-color:#ADFF2F;">
<%=form_for @post,:url=>user_post_path(@user) do |f|%>
<h2 style="font-family:verdana;color:#228B22;"><%=f.label :title%>
<%=f.text_field :title%></h2>
<h2 style="font-family:verdana;color:#228B22;"><%=f.label :description%>
<%=f.text_field :description%></h2>
<%= f.submit "Update Post"%>
<%end%>
</body>
</html>

atrayi/app/views/posts/index.html.erb
<body style="background-color:#DDA0DD;">
<%@posts.each do |post|%>
Title:<%=post.title%>
<%=link_to "Show Post..",user_post_path(@user,post)%>
<br>
<hr>

<%end%>
</body>

atrayi/app/views/posts/new.html.erb
<html>
<body style="background-color:#98FB98;">
<%=form_for @post,:url=>user_posts_path do |f|%>
<h2 style="font-family:verdana;color:#800080;"><%=f.label :title%>
<%=f.text_field :title%></h2>
<h2 style="font-family:verdana;color:#800080;"><%=f.label :description%>
<%=f.text_field :description%></h2>
<%= f.submit "Create Post"%>
<%end%>
</body>
</html>

atrayi/app/views/posts/show.html.erb
<body style="background-color:#ADD8E6;">
<h4 style="font-family:verdana;color:#8B0000;">Title:&nbsp;&nbsp;<%=@post.title%><br>
Description:&nbsp;&nbsp;<%=@post.description%><br>
<%=link_to "edit post",edit_user_post_path(@user,@post)%>&nbsp;&nbsp;
<%=link_to "delete post",user_post_path(@user,@post),:method=>:delete%>
<hr></h4>

</body>

atrayi/app/views/users/edit.html.erb
<body style="background-color:#B0E0E6;">
<%=form_for @user do |f|%>
<h3 style="font-family:verdana;color:#800080;"><%=f.label :name%>
<%=f.text_field :name%></h3>
<h3 style="font-family:verdana;color:#800080;"><%=f.label :email%>
<%=f.email_field :email%></h3>
<h3 style="font-family:verdana;color:#800080;"><%=f.label :dept%>
<%=f.text_field :dept%></h3>
<h3 style="font-family:verdana;color:#800080;"><%=f.label :roll%>
<%=f.text_field :roll%></h3>
<h3 style="font-family:verdana;color:#800080;"><%=f.label :age%>
<%=f.text_field :age%></h3>
<h3 style="font-family:verdana;color:#800080;"><%=f.label :contact_no%>
<%=f.text_field :contact_no%></h3>
<%=f.submit "Update"%>

<%end%>
</body>

atrayi/app/views/users/index.html.erb
<body style="background-color:#ADD8E6;">
<%@users.each do|u|%>
	<h4 style="font-family:verdana;color:#8B0000;">Name:&nbsp;&nbsp;&nbsp;<%=u.name%>&nbsp;&nbsp;&nbsp;&nbsp;
	Email:&nbsp;&nbsp;&nbsp;<%=u.email%></h4>
  	<%=link_to "Show",user_path(u)%>&nbsp;&nbsp;
  	<%=link_to "Edit",edit_user_path(u)%>&nbsp;&nbsp;
	<%=link_to "Delete",user_path(u),:method=>:delete%><br>
<%end%>
<%=link_to "create User",new_user_path%>
</body>

atrayi/app/views/users/new.html.erb
<body style="background-color:#ADFF2F;">
<%=form_for @user do |f|%>
<h3 style="font-family:verdana;color:#0066CC;"><%=f.label :name%>
<%=f.text_field :name%></h3>
<h3 style="font-family:verdana;color:#0066CC;"><%=f.label :email%>
<%=f.email_field :email%></h3>
<h3 style="font-family:verdana;color:#0066CC;"><%=f.label :dept%>
<%=f.text_field :dept%></h3>
<h3 style="font-family:verdana;color:#0066CC;"><%=f.label :roll%>
<%=f.text_field :roll%></h3>
<h3 style="font-family:verdana;color:#0066CC;"><%=f.label :age%>
<%=f.text_field :age%></h3>
<h3 style="font-family:verdana;color:#0066CC;"><%=f.label :contact_no%>
<%=f.text_field :contact_no%></h3>
<%=f.submit%>
</body>

<%end%>

atrayi/app/views/users/show.html.erb
<body style="background-color:#DDA0DD;">
<h4 style="font-family:verdana;color:#8B0000;">Name:&nbsp;&nbsp;&nbsp;<%=@user.name %>&nbsp;&nbsp;<br>
Email:&nbsp;&nbsp;&nbsp;<%=@user.email%>&nbsp;&nbsp;<br>
Roll:&nbsp;&nbsp;&nbsp;<%=@user.roll%>&nbsp;&nbsp;<br>
Dept.:&nbsp;&nbsp;&nbsp;<%=@user.dept%>&nbsp;&nbsp;<br>
Age:&nbsp;&nbsp;&nbsp;<%=@user.age%>&nbsp;&nbsp;<br>
Contact:&nbsp;&nbsp;&nbsp;<%=@user.contact_no%><br></h4>
<%=link_to "Edit", edit_user_path(@user)%>&nbsp;&nbsp;
<%=link_to "Delete", user_path(@user), :method=>:delete %>&nbsp;&nbsp;
<%=link_to "Post",new_user_post_path(@user)%>&nbsp;&nbsp;
<%=link_to "See Posts...",user_posts_path(@user)%><br>